[project]
name    = "heliodor"
version = "0.1.0"

[build]
clock_type  = "posedge"
reset_type  = "async_low"
sources     = ["src", "tb"]
evaluate_size_limit = 8388608  # 8M (for 16MB DRAM = 4194304 × 32-bit words)

[test]
simulator = "verilator"
