#!/usr/bin/env python3
"""Generate tb/test_arch.veryl with one harness + #[test] per ISA test.

Scans test/riscv-arch-test/build/<suite>/*.hex and emits a single Veryl
file with the necessary boilerplate. Run from the heliodor project root:

    python3 test/riscv-arch-test/gen_tb.py
"""
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
BUILD_ROOT = os.path.join(ROOT, "test", "riscv-arch-test", "build")
OUT = os.path.join(ROOT, "tb", "test_arch.veryl")

SUITES = ["rv64ui", "rv64um", "rv64ua", "rv64uc", "rv64uf", "rv64ud", "rv64mi", "rv64si"]

HEADER = '''// AUTOGENERATED by test/riscv-arch-test/gen_tb.py — DO NOT EDIT BY HAND.
//
// riscv-tests ISA test harnesses.  Each test has a dedicated harness
// because the Veryl simulator currently requires `$readmemh` to take a
// string literal (cannot be parameterized).  Each harness loads the
// corresponding hex file from test/riscv-arch-test/build/<suite> into a
// 1 MB DRAM at PA 0x80000000 and runs heliodor_top.  The riscv-tests
// "p" environment writes to a tohost word at PA 0x80001000:
//   tohost == 1  → all subtests passed
//   tohost  > 1  → subtest with that ID failed
'''


HARNESS_TEMPLATE = '''
module test_arch_{suite}_{name}_harness (
    clk     : input  clock    ,
    rst     : input  reset    ,
    o_pass  : output logic    ,
    o_fail  : output logic    ,
    o_tohost: output logic<32>,
) {{
    var imem_addr : logic<64>     ;
    var imem_rdata: logic<32>     ;
    var imem_ren  : logic         ;
    var dmem_addr : logic<64>     ;
    var dmem_wdata: logic<64>     ;
    var dmem_rdata: logic<64>     ;
    var dmem_wen  : logic         ;
    var dmem_ren  : logic         ;
    var dmem_wstrb: logic<8>      ;
    var dbg_regs  : logic<64> [32];
    var dbg_pc    : logic<64>     ;
    var dbg_pass  : logic         ;
    var dbg_r1    : logic<64>     ;
    var dbg_r2    : logic<64>     ;
    var dbg_r3    : logic<64>     ;
    var iptw_addr : logic<64>     ;
    var iptw_req  : logic         ;
    var iptw_rdata: logic<64>     ;

    inst dut: heliodor_top #(
        RESET_PC: 64'h80000000,
    )(
        clk                        ,
        rst                        ,
        o_imem_addr    : imem_addr ,
        i_imem_rdata   : imem_rdata,
        o_imem_ren     : imem_ren  ,
        o_iptw_addr    : iptw_addr ,
        o_iptw_req     : iptw_req  ,
        i_iptw_rdata   : iptw_rdata,
        i_uart_rx_data : 8'd0      ,
        i_uart_rx_valid: 1'b0      ,
        o_dmem_addr    : dmem_addr ,
        o_dmem_wdata   : dmem_wdata,
        i_dmem_rdata   : dmem_rdata,
        o_dmem_wen     : dmem_wen  ,
        o_dmem_ren     : dmem_ren  ,
        o_dmem_wstrb   : dmem_wstrb,
        o_dbg_regs     : dbg_regs  ,
        o_dbg_pc       : dbg_pc    ,
        o_dbg_pass     : dbg_pass  ,
        o_dbg_r1       : dbg_r1    ,
        o_dbg_r2       : dbg_r2    ,
        o_dbg_r3       : dbg_r3    ,
        i_ext_irq      : 32'd0     ,
    );

    var dram: logic<32> [262144];
    initial {{
        $readmemh("test/riscv-arch-test/build/{suite}/{file}.hex", dram);
    }}

    let in_dram      : logic     = dmem_addr[31];
    let dram_imem_idx: logic<18> = imem_addr[19:2];
    let dram_dmem_lo : logic<18> = {{dmem_addr[19:3], 1'b0}};
    let dram_dmem_hi : logic<18> = {{dmem_addr[19:3], 1'b1}};

    assign imem_rdata = if imem_addr[31] ? dram[dram_imem_idx] : 32'd0;
    assign dmem_rdata = if in_dram ? {{dram[dram_dmem_hi], dram[dram_dmem_lo]}} : 64'd0;

    let dram_iptw_lo: logic<18> = {{iptw_addr[19:3], 1'b0}};
    let dram_iptw_hi: logic<18> = {{iptw_addr[19:3], 1'b1}};
    assign iptw_rdata = if iptw_addr[31] ? {{dram[dram_iptw_hi], dram[dram_iptw_lo]}} : 64'd0;

    always_ff (clk, rst) {{
        if_reset {{}} else if dmem_wen && in_dram {{
            if dmem_wstrb[0] {{
                dram[dram_dmem_lo][7:0] = dmem_wdata[7:0];
            }}
            if dmem_wstrb[1] {{
                dram[dram_dmem_lo][15:8] = dmem_wdata[15:8];
            }}
            if dmem_wstrb[2] {{
                dram[dram_dmem_lo][23:16] = dmem_wdata[23:16];
            }}
            if dmem_wstrb[3] {{
                dram[dram_dmem_lo][31:24] = dmem_wdata[31:24];
            }}
            if dmem_wstrb[4] {{
                dram[dram_dmem_hi][7:0] = dmem_wdata[39:32];
            }}
            if dmem_wstrb[5] {{
                dram[dram_dmem_hi][15:8] = dmem_wdata[47:40];
            }}
            if dmem_wstrb[6] {{
                dram[dram_dmem_hi][23:16] = dmem_wdata[55:48];
            }}
            if dmem_wstrb[7] {{
                dram[dram_dmem_hi][31:24] = dmem_wdata[63:56];
            }}
        }}
    }}

    let tohost_lo: logic<32> = dram[18'd{tohost_idx}];
    assign o_tohost = tohost_lo;
    assign o_pass = tohost_lo == 32'd1;
    assign o_fail = tohost_lo[0] == 1'b0 && tohost_lo != 32'd0;
}}

#[test(test_arch_{suite}_{name})]
#[ignore]
module test_arch_{suite}_{name} {{
    inst clk: $tb::clock_gen;
    inst rst: $tb::reset_gen;

    var pass  : logic    ;
    var fail  : logic    ;
    var tohost: logic<32>;

    inst h: test_arch_{suite}_{name}_harness (
        clk              ,
        rst              ,
        o_pass  : pass   ,
        o_fail  : fail   ,
        o_tohost: tohost ,
    );

    initial {{
        rst.assert(clk);
        clk.next  (200000);
        $display  ("{suite}-{name} tohost=%h pass=%b fail=%b", tohost, pass, fail);
        $assert   (pass, "{suite}-{name}: tohost did not signal pass");
        $display  ("{suite}-{name} test passed");
        $finish   ();
    }}
}}
'''


def tohost_index(elf_path):
    """Return dram-word index of `tohost` symbol, computed from an ELF file.

    dram is organized as logic<32>[262144] covering PA 0x80000000..+1MB, so
    index = (tohost_vaddr - 0x80000000) / 4. Falls back to 1024 (0x80001000,
    the default for the standard "p" link.ld) if nm is unavailable or the
    symbol is missing."""
    default = 1024
    if not os.path.exists(elf_path):
        return default
    try:
        out = subprocess.check_output(
            ["riscv64-unknown-elf-nm", elf_path], stderr=subprocess.DEVNULL
        ).decode()
    except (FileNotFoundError, subprocess.CalledProcessError):
        return default
    for line in out.splitlines():
        parts = line.split()
        if len(parts) >= 3 and parts[-1] == "tohost":
            addr = int(parts[0], 16)
            return (addr - 0x80000000) // 4
    return default


def main():
    out = [HEADER]
    total = 0
    for suite in SUITES:
        build_dir = os.path.join(BUILD_ROOT, suite)
        if not os.path.isdir(build_dir):
            print(f"skip {suite}: not built", file=sys.stderr)
            continue
        names = sorted(
            os.path.splitext(f)[0]
            for f in os.listdir(build_dir)
            if f.endswith(".hex")
        )
        for n in names:
            elf = os.path.join(build_dir, f"{n}.elf")
            idx = tohost_index(elf)
            ident = n.replace("-", "_")
            out.append(
                HARNESS_TEMPLATE.format(
                    suite=suite, name=ident, file=n, tohost_idx=idx
                )
            )
            total += 1

    if total == 0:
        sys.exit("no .hex files found; run `make -C test/riscv-arch-test` first")

    with open(OUT, "w") as f:
        f.write("\n".join(out))

    print(f"wrote {OUT} with {total} test harnesses")


if __name__ == "__main__":
    main()
