#!/usr/bin/env python3
"""Generate tb/test_arch.veryl with one harness + #[test] per ISA test.

Scans test/riscv-arch-test/build/<suite>/*.hex and emits a single Veryl
file with the necessary boilerplate. Run from the heliodor project root:

    python3 test/riscv-arch-test/gen_tb.py
"""
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
BUILD_ROOT = os.path.join(ROOT, "test", "riscv-arch-test", "build")
OUT = os.path.join(ROOT, "tb", "test_arch.veryl")

SUITES = ["rv64ui", "rv64um", "rv64ua", "rv64uc", "rv64uf", "rv64ud", "rv64mi", "rv64si"]

# Suites that run by default (not marked #[ignore]).  The basic
# integer and M-extension suites are fast enough to include in the
# default `veryl test` regression; the FP / atomic / privileged
# suites are slower and stay ignored.
FAST_SUITES = {
    "rv64ui",
    "rv64um",
    "rv64ua",
    "rv64uc",
    "rv64uf",
    "rv64ud",
    "rv64mi",
    "rv64si",
}

HEADER = '''// AUTOGENERATED by test/riscv-arch-test/gen_tb.py — DO NOT EDIT BY HAND.
//
// Each per-test module below is a thin wrapper that instantiates the
// shared harness in tb/test_arch_common.veryl with its own HEX_FILE
// and TOHOST_IDX.  Collapsing the 60-line boilerplate into a single
// shared module dramatically reduces the amount of source `veryl test`
// has to parse.
'''


HARNESS_TEMPLATE = '''
#[test(test_arch_{suite}_{name})]
{ignore_attr}module test_arch_{suite}_{name} {{
    inst clk: $tb::clock_gen;
    inst rst: $tb::reset_gen;

    var pass  : logic    ;
    var fail  : logic    ;
    var tohost: logic<32>;

    inst h: test_arch_common_harness #(
        HEX_FILE  : "test/riscv-arch-test/build/{suite}/{file}.hex",
        TOHOST_IDX: {tohost_idx},
    ) (
        clk              ,
        rst              ,
        o_pass  : pass   ,
        o_fail  : fail   ,
        o_tohost: tohost ,
    );

    initial {{
        rst.assert(clk);
        clk.next  (200000);
        $display  ("{suite}-{name} tohost=%h pass=%b fail=%b", tohost, pass, fail);
        $assert   (pass, "{suite}-{name}: tohost did not signal pass");
        $display  ("{suite}-{name} test passed");
        $finish   ();
    }}
}}
'''


def tohost_index(elf_path):
    """Return dram-word index of `tohost` symbol, computed from an ELF file.

    dram is organized as logic<32>[262144] covering PA 0x80000000..+1MB, so
    index = (tohost_vaddr - 0x80000000) / 4. Falls back to 1024 (0x80001000,
    the default for the standard "p" link.ld) if nm is unavailable or the
    symbol is missing."""
    default = 1024
    if not os.path.exists(elf_path):
        return default
    try:
        out = subprocess.check_output(
            ["riscv64-unknown-elf-nm", elf_path], stderr=subprocess.DEVNULL
        ).decode()
    except (FileNotFoundError, subprocess.CalledProcessError):
        return default
    for line in out.splitlines():
        parts = line.split()
        if len(parts) >= 3 and parts[-1] == "tohost":
            addr = int(parts[0], 16)
            return (addr - 0x80000000) // 4
    return default


def main():
    out = [HEADER]
    total = 0
    for suite in SUITES:
        build_dir = os.path.join(BUILD_ROOT, suite)
        if not os.path.isdir(build_dir):
            print(f"skip {suite}: not built", file=sys.stderr)
            continue
        names = sorted(
            os.path.splitext(f)[0]
            for f in os.listdir(build_dir)
            if f.endswith(".hex")
        )
        ignore_attr = "" if suite in FAST_SUITES else "#[ignore]\n"
        for n in names:
            elf = os.path.join(build_dir, f"{n}.elf")
            idx = tohost_index(elf)
            ident = n.replace("-", "_")
            out.append(
                HARNESS_TEMPLATE.format(
                    suite=suite,
                    name=ident,
                    file=n,
                    tohost_idx=idx,
                    ignore_attr=ignore_attr,
                )
            )
            total += 1

    if total == 0:
        sys.exit("no .hex files found; run `make -C test/riscv-arch-test` first")

    with open(OUT, "w") as f:
        f.write("\n".join(out))

    print(f"wrote {OUT} with {total} test harnesses")


if __name__ == "__main__":
    main()
