#!/usr/bin/env python3
"""Generate heliodor ACT4 hex + Veryl batch test for one extension.

Usage: gen_suite.py <EXT> [<EXT2> ...]
  - globs ACT4 ELFs under $ACT_WORK/elfs/**/<EXT>/*.elf
  - objcopy -> flat bin -> test/hex/act_<extlc>_<name>.hex
  - writes tb/test_act_<extlc>.veryl with one #[test] module per ELF

Paths come from the environment (set by `source toolchain/env.sh` and the
test/act Makefile):
  ACT_WORK   ACT4 framework work dir holding elfs/  (default: upstream/riscv-arch-test-act/work/heliodor)
  OBJCOPY    riscv elf objcopy                      (default: riscv64-unknown-elf-objcopy on PATH)
"""
import os, re, subprocess, sys, glob

HERE = os.path.dirname(os.path.abspath(__file__))          # <repo>/test/act
REPO = os.path.normpath(os.path.join(HERE, "..", ".."))    # <repo>
ACT_WORK = os.environ.get("ACT_WORK",
                          os.path.join(HERE, "upstream", "riscv-arch-test-act", "work", "heliodor"))
OBJCOPY = os.environ.get("OBJCOPY", "riscv64-unknown-elf-objcopy")
BIN2HEX = os.path.join(REPO, "test", "c", "bin2hex.py")
BINDIR  = os.path.join(HERE, "build", "bin")

def sanitize(s):
    return re.sub(r'[^0-9a-zA-Z]', '_', s)

def gen(ext):
    extlc = ext.lower()
    elfs = sorted(glob.glob(f"{ACT_WORK}/elfs/**/{ext}/*.elf", recursive=True))
    if not elfs:
        print(f"  [{ext}] no ELFs found under {ACT_WORK}/elfs/**/{ext}/"); return None
    os.makedirs(BINDIR, exist_ok=True)
    mods = []
    for elf in elfs:
        base = os.path.basename(elf)[:-4]                       # e.g. I-addi-00
        m = re.match(rf'^{re.escape(ext)}-(.+)$', base)
        short = sanitize(m.group(1)) if m else sanitize(base)   # addi_00
        binf = f"{BINDIR}/{extlc}_{short}.bin"
        hexf = f"{REPO}/test/hex/act_{extlc}_{short}.hex"
        subprocess.run([OBJCOPY, "-O", "binary", elf, binf], check=True)
        subprocess.run(["python3", BIN2HEX, binf, hexf], check=True,
                       stdout=subprocess.DEVNULL)
        mods.append((short, f"test/hex/act_{extlc}_{short}.hex"))

    out = []
    out.append(f"// ACT4 (riscv-arch-test) {ext}-extension compliance suite on the OoO core.")
    out.append(f"// GENERATED by test/act/gen_suite.py from ACT4 Sail-signed ELFs — do not edit.")
    out.append(f"// heliodor DUT config: tohost @0x80001000 (TOHOST_IDX 1024), HALT fence.i.")
    out.append(f"// tohost == 1 means the self-check passed. Regenerate via `make -C test/act`.")
    out.append("")
    for short, hexf in mods:
        mod = f"test_act_{extlc}_{short}"
        out += [
            f"#[test({mod})]",
            f"#[ignore]",
            f"module {mod} {{",
            f"    inst clk: $tb::clock_gen;",
            f"    inst rst: $tb::reset_gen ( clk );",
            f"    var pass  : logic    ;",
            f"    var fail  : logic    ;",
            f"    var tohost: logic<32>;",
            f"    inst h: test_arch_common_harness #(",
            f'        HEX_FILE  : "{hexf}",',
            f"        TOHOST_IDX: 1024,",
            f"    ) (",
            f"        clk             ,",
            f"        rst             ,",
            f"        o_pass  : pass  ,",
            f"        o_fail  : fail  ,",
            f"        o_tohost: tohost,",
            f"    );",
            f"    initial {{",
            f"        rst.assert(clk);",
            f"        clk.next  (300000);",
            f'        $display  ("ACT4 {ext}-{short} tohost=%h pass=%b", tohost, pass);',
            f'        $assert   (pass, "ACT4 {ext}-{short} fail");',
            f'        $display  ("ACT4 {ext}-{short} PASS");',
            f"        $finish   ();",
            f"    }}",
            f"}}",
            "",
        ]
    verylf = f"{REPO}/tb/test_act_{extlc}.veryl"
    open(verylf, "w").write("\n".join(out))
    print(f"  [{ext}] {len(mods)} tests -> tb/test_act_{extlc}.veryl")
    return extlc

if __name__ == "__main__":
    if len(sys.argv) < 2:
        sys.exit("usage: gen_suite.py <EXT> [<EXT2> ...]")
    for ext in sys.argv[1:]:
        gen(ext)
